Add Relay Dockerfile
bosagora/dms-osx pull request #102
Opened 2023-08-24 06:26 UTC by TrustHenry

2023-08-24 06:33 UTC, Kang-Simon approved these changes
LGTM

2023-08-28 01:37 UTC, MichaelKim20 requested changes
1. dms-chain에 추가된 docker-compose.yml에는 환경변수 RPC_URL가 사용되었습니다. 그기에 맞게 이곳의 DEV_NET_URL를 RPC_URL로 변경해 주세요
2. config.yaml에서 manager_key를 등록하기 위해서 사용된 환경변수 MANAGER를 설정한 부분이 없습니다.
MANAGER_KEY로 변경해주시고요 이값은 아래 값을 사용해주세요
  {
    "address": "0x454cd944C9Eac1e84064c0D105931aDCEbC86c89",
    "privateKey": "0xf17b5048d0acdcabcc1fa5f3e1aa6753243d4309a6a30f951d5712cb50c86671"
  },

2023-08-28 01:37 UTC, MichaelKim20 commented on packages/relay/env/.env.sample
> +DEV_NET_URL=http://localhost:8545
```suggestion
RPC_URL=http://localhost:8545
```

2023-08-28 01:37 UTC, MichaelKim20 commented on packages/relay/hardhat.config.ts
> +            url: process.env.DEV_NET_URL || "",
```suggestion
            url: process.env.RPC_URL || "",
```

2023-08-28 02:18 UTC, TrustHenry commented on packages/relay/env/.env.sample
> +DEV_NET_URL=http://localhost:8545
1 ,2 번 적용 되었습니다.

2023-08-28 02:21 UTC, MichaelKim20 approved these changes
MANAGER 로 된 코드가 하나더 있네요

2023-08-28 02:21 UTC, MichaelKim20 commented on packages/relay/hardhat.config.ts
>          process.env.MANAGER = Wallet.createRandom().privateKey;
```suggestion
        process.env.MANAGER_KEY = Wallet.createRandom().privateKey;
```

2023-08-28 02:22 UTC, TrustHenry commented on packages/relay/hardhat.config.ts
>          process.env.MANAGER = Wallet.createRandom().privateKey;
Thx, Nice catch!

2023-08-28 02:23 UTC, merged