Add dms-osx Relay endpoint payMileage
bosagora/dms-osx pull request #92
Opened 2023-08-16 08:45 UTC by TrustHenry

POST /payMileage
Add the Restful API router
Relay implementation calling payMileage of Ledger contract

2023-08-16 08:46 UTC, TrustHenry commented
Test 코드 구현은 Next!

2023-08-17 05:54 UTC, TrustHenry commented on packages/relay/src/routers/DefaultRouter.ts
> +            // TODO 서명검증
반영되었습니다.

2023-08-18 05:28 UTC, MichaelKim20 requested changes
현재는 
{
  code: 400,
  error: {
    validation: [ [Object], [Object] ],
    message: 'Failed to check the validity of parameters.'
  }
}

와 같은 응답이 나오네요 응답코드와 결과도 확인이 필요하네요

2023-08-18 05:42 UTC, MichaelKim20 requested changes

2023-08-18 05:42 UTC, MichaelKim20 commented on packages/relay/test/Endpoints.test.ts
> +                const amt = purchaseAmount.div(100);
제거해주세요

2023-08-18 05:42 UTC, MichaelKim20 commented on packages/relay/test/Endpoints.test.ts
> +                    amt,
```suggestion
                    purchaseAmount,
```

2023-08-18 05:42 UTC, MichaelKim20 commented on packages/relay/test/Endpoints.test.ts
> +                    amount: amt,
```suggestion
                    amount: purchaseAmount.toString(),
```

2023-08-18 05:42 UTC, MichaelKim20 commented on packages/relay/src/routers/DefaultRouter.ts
> +                body("email").exists().matches(reg_bytes64),
```suggestion
                body("email").exists().matches(/^(0x)[0-9a-f]{64}$/i),
```

2023-08-18 05:42 UTC, MichaelKim20 commented on packages/relay/src/routers/DefaultRouter.ts
> +                body("signature").exists().matches(reg_bytes130),
```suggestion
                body("signature").exists().matches(/^(0x)[0-9a-f]{130}$/i),
```

2023-08-18 06:34 UTC, TrustHenry commented on packages/relay/test/Endpoints.test.ts
> +                const amt = purchaseAmount.div(100);
100 으로 나누어야 마일리지 잔액과 동일해서요. Pay 가 되더라구요.

2023-08-18 06:48 UTC, TrustHenry commented on packages/relay/test/Endpoints.test.ts
> +                const amt = purchaseAmount.div(100);
반영 되었습니다.

2023-08-18 07:30 UTC, MichaelKim20 requested changes
테스트를 위해 이미 토큰을 예치하고 그것을 마일리지로 교환해 두었습니다.
그것을 사용해 주세요

2023-08-18 07:30 UTC, MichaelKim20 commented on packages/relay/test/Endpoints.test.ts
> +    context("Pay mileage", () => {
이 테스트 컨텍스트를 내부의 context("POST /payMileage"...) 만을 이전 컨텍스트 안에 추가해 주세요

2023-08-18 07:35 UTC, MichaelKim20 requested changes

2023-08-18 07:35 UTC, MichaelKim20 commented on packages/relay/test/Endpoints.test.ts
> +                assert.deepStrictEqual(response.data.code, 200);
```suggestion
                assert.deepStrictEqual(response.data.code, 200);
                assert.ok(response.data.data !== undefined);
                assert.ok(response.data.data.txHash !== undefined);                
```

2023-08-18 07:41 UTC, MichaelKim20 commented
오류가 발생하는 테스트코드도 추가해 주세요
1. 잔고부족시 발생하는 오류
2. 등록되지 않은 이메일을 사용할 경우
3. 서명이 잘못되었을 경우

2023-08-18 07:46 UTC, MichaelKim20 commented on packages/relay/src/routers/DefaultRouter.ts
> +                    error,
error 의 error.message 만을 전달해 주세요.
만약 error.message가 없다면 "Failed pay mileage."를 사용하면 되겠습니다.
에러도 코드가 있다면 좋겠습니다.

2023-08-18 08:15 UTC, TrustHenry commented on packages/relay/src/routers/DefaultRouter.ts
> +                    error,
error.message 가 없더라구요.  
require 메세지를 뽑아내려면 error 메세지를 파싱 해야할듯 합니다.
Failed pay mileage. 만 반환하겠습니다.

2023-08-21 06:23 UTC, TrustHenry commented
> 오류가 발생하는 테스트코드도 추가해 주세요
> 
> 1. 잔고부족시 발생하는 오류
> 2. 등록되지 않은 이메일을 사용할 경우
> 3. 서명이 잘못되었을 경우

테스트코드를 추가 하였습니다.

2023-08-21 06:37 UTC, MichaelKim20 approved these changes
LGTM

2023-08-21 06:37 UTC, merged